// Automatically generated by astro-icon
// e88c45eb03b1de31d3f5d56915d3899b508006ccf47f47e495cafb2e37efb557

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "microsoft"
		| "microsoft-xbox"
		| "open-in-new"
		| "riotgames"
		| "sony-playstation"
		| "steam"
		| "twitch"
		| "twitter"
		| "youtube";
}